# vim: set filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2 background=dark :

- name: enable database cluster resource
  shell: pcs resource enable "{{ postgres_ha_cluster_pg_HA_res_name }}" 
  when: inventory_hostname == postgres_ha_cluster_master_host    # run only on one node

- name: refresh database cluster resource
  shell: pcs resource manage "{{ postgres_ha_cluster_pg_HA_res_name }}" && pcs resource clear "{{ postgres_ha_cluster_pg_HA_res_name }}" && pcs resource refresh "{{ postgres_ha_cluster_pg_HA_res_name }}"
  when: inventory_hostname == postgres_ha_cluster_master_host    # run only on one node

- name: check if all slaves are connected
  shell: psql -Aqtc "SELECT count(*) FROM pg_stat_replication"
  when: inventory_hostname == postgres_ha_cluster_master_host    # run only on one node
  become: yes
  become_user: postgres
  register: slavecount
  vars:
    ansible_ssh_pipelining: no
  until: (slavecount.stdout|string) == ((ansible_play_batch|length - 1)|string)
  retries: 16
  delay: 2

